### ISSUE TITLE
infografiafernanda

### ISSUE THREAD

**Issue by 27Fer12** [SistemasTecTlaxiaco/actividad-1-infografia-27Fer12#2]
[Infografía de ciclo de vida de un sistema.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-27Fer12/files/12489408/Infografia.de.ciclo.de.vida.de.un.sistema.pdf)

**Comment by Alvaro2-0** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
